### PR TITLE
Add customize ui v2

### PR DESCRIPTION
**Pull request by xmaillard**
@cvmat this is my second attempt.

I had really big problems with git here. I hope this one is the good one.

This should close #97 

Keep up the good work.
Xavier

### CODE REVIEW

**Comment by xmaillard** [comment]
Any news ?

Regards

**Comment by cvmat** [comment]
The patch dd3cfae9ad16cb7aef47dc5a5efa8387e1b9db0d adds TAB to docstrings and comments.

Some whitespaces in the credits and comments describing timeline spec as S-expression, placed at the 4511-th line of dd3cfae9ad16cb7aef47dc5a5efa8387e1b9db0d , are replaced with a TAB. Since Emacs does not automatically indent in comments (on my env at least), I have used whitespaces in comments.

Is the above modification one of a convention? Or is it required to suppress errors from some document checking tool?

I have checked some Emacs LISP files distributed with Emacs.
In `gnus.el`, the docstring of the variable `gnus-group-faq-directory` are indented with TABs but that of the macro `gnus-define-group-parameter` are indented with whitespaces only.

For ease of editing, I want not to use TABs in docstrings and comments if possible.

Can I import your work with my modification?

(I will also fix the credit because twittering-mode does not include
 works in the years 2012-2015 by Mr. Hayamizu.)

**Comment by xmaillard** [comment]
Off course. I think my setup is misconfigured concerning the whitespace/TAB conventions. I have tried to fix as many things as I could.

You can effectively import my changes with my modifications.

Regards
Xavier

**Comment by cvmat** [comment]
I have imported your work at a18606d6123159083b3ace8427aa53f3ca6a7eb4 (and I fixed it in 58f4e602d7695dfeda79a4e5a7a28e8d495070f7 ) . Please check it.

**Comment by xmaillard** [comment]
AFAICT, it is good.

Thank you. I will publish something smaller next time ^^

Regards

**Pull request closed without merging**
