### PR TITLE
Bugfix: wrong number of arguments

### PR DESCRIPTION
**Pull request by TheBB**
See https://github.com/syl20bnr/spacemacs/issues/6362

### CODE REVIEW

**Comment by j0ni** [comment]
Hey @hayamiz, any chance this could get merged? It's super simple, and fixes an annoying bug.

(Sorry to be a squeaky wheel - and thanks for the useful package).

**Comment by hayamiz** [comment]
@j0ni thanks for your pull request, but I've been away from twmode development for years, and currently @cvmat is the most active maintainer.

**Comment by j0ni** [comment]
@hayamiz not my pull request but thanks for setting me straight. @cvmat any chance of getting this merged?

**Comment by cvmat** [comment]
I am sorry for taking so long to reply.
I have thought that it is caused by incompatibility of Spacemacs because the code
`(setq var)` works in Emacs without errors.
However, such code is certainly not intuitive.
I have merged the patch.
Thank you for the contribution.

**Comment by cvmat** [comment]
@TheBB 
I will add an entry for this patch to the ChangeLog file later.
Can I mention your name in the entry?

**Comment by j0ni** [comment]
Thanks for merging this.

FWIW, I do not use spacemacs, and I've been seeing this in emacs 26.0.50 (current `master`). Perhaps it's a recent change in emacs. Either way, I agree, it is not intuitive.

**Comment by TheBB** [comment]
Sure, you can mention my name

**Pull request merged**
